from django.db import models
import json
# # Create your models here.
class Champ(models.Model):
    class Meta:
        db_table = "champ"
    name = models.CharField(max_length=20)
    lane = models.CharField(max_length=20)
    skill = models.TextField()
    skilltree = models.CharField(max_length=200)
    skilltrees = models.CharField(max_length=200)
    skillpick = models.CharField(max_length=200)
    skillwin = models.CharField(max_length=200)
    s_item1 = models.TextField()
    s_itempick1 = models.CharField(max_length=200)
    s_itemwin1 = models.CharField(max_length=200)
    s_item2 = models.TextField()
    s_itempick2 = models.CharField(max_length=200)
    s_itemwin2 = models.CharField(max_length=200)
    s_shoe1 = models.TextField()
    s_shoepick1 = models.CharField(max_length=200)
    s_shoewin1 = models.CharField(max_length=200)
    s_shoe2 = models.TextField()
    s_shoepick2 = models.CharField(max_length=200)
    s_shoewin2 = models.CharField(max_length=200)
    item1 = models.TextField()
    itempick1 = models.CharField(max_length=200)
    itemwin1 = models.CharField(max_length=200)
    item2 = models.TextField()
    itempick2 = models.CharField(max_length=200)
    itemwin2 = models.CharField(max_length=200)
    item3 = models.TextField()
    itempick3 = models.CharField(max_length=200)
    itemwin3 = models.CharField(max_length=200)
    item4 = models.TextField()
    itempick4 = models.CharField(max_length=200)
    itemwin4 = models.CharField(max_length=200)
    item5 = models.TextField()
    itempick5 = models.CharField(max_length=200)
    itemwin5 = models.CharField(max_length=200)
    hard_img = models.TextField()
    hard_win = models.CharField(max_length=200)
    easy_img = models.TextField()
    easy_win = models.CharField(max_length=200)
    rune_j = models.TextField()
    rune_js = models.TextField()
    rune_j_name = models.CharField(max_length=200)
    rune_k = models.TextField()
    rune_ks = models.TextField()
    rune_k_name = models.CharField(max_length=200)
    rune_n = models.TextField()
    rune_n_name = models.CharField(max_length=200)
    rune_img1 = models.TextField()
    rune_pick1 = models.CharField(max_length=200)
    rune_win1 = models.CharField(max_length=200)
    rune_img2 = models.TextField()
    rune_pick2 = models.CharField(max_length=200)
    rune_win2 = models.CharField(max_length=200)
    def __str__(self):
        return f"{self.name}"

